### ISSUE TITLE
PaymentCreateOptions Currency

### ISSUE THREAD

**Issue by burakoner** [paparateam/merchantApiClient-dotnet#1]
Merhaba

PaymentCreateOptions modelinde dokümantasyonda yer alan currency parametresi eksik. Bu haliyle yalnızca Türk Lirası için payment oluşturulabiliyor. Kontrol etmeniz mümkün müdür acaba?

İyi çalışmalar.

**Comment by burakoner** [comment]
Aynı durum MassPaymentToPaparaNumberOptions için de geçerli

**Comment by papara-admin** [comment]
Teşekkür ederiz, konuyu gündemimize aldık.

**Comment by burakoner** [comment]
teşekkürler
